...
x-env:
  - &zookeeper-username '${ZOOKEEPER_USERNAME}'
  - &zookeeper-password '${ZOOKEEPER_PASSWORD}'
  - &kafka-username '${KAFKA_USERNAME}'
  - &kafka-password '${KAFKA_PASSWORD}'

services:
  ...
  kafka:
    image: bitnami/kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'localhost:2181'
      KAFKA_ZOOKEEPER_USER: *zookeeper-username
      KAFKA_ZOOKEEPER_PASSWORD: *zookeeper-password
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENERS: 'SASL_PLAINTEXT://:9092'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://:9092'
      KAFKA_BROKER_USER: *kafka-username
      KAFKA_BROKER_PASSWORD: *kafka-password
      KAFKA_CFG_NUM_PARTITIONS: 4
      KAFKA_CFG_NUM_NETWORK_THREADS: 16

